# open api start
run:
		docker-compose down && docker-compose up -d && open http://localhost:8012

# gitbook document build
book.build:
		cd docbook && gitbook build

# gitbook document start
book.start:
		cd docbook && gitbook serve
