# open api start
run:
		docker-compose down && docker-compose up -d && open http://localhost:8012

# gitbookk document build
book.build:
		cd docbook && gitbook build

# gitbookk document start
book.start:
		cd docbook && gitbook serve
